### ISSUE TITLE
[BUG] Canvas Comics not showing up on Webtoon

### ISSUE THREAD

**Issue by gimmeamin** [TheNetsky/extensions-sources#40]
**Describe the bug**
When using the webtoon extension, only the original comics show up. The canvas doesn’t.

**To Reproduce**
1. Go to ‘Search’

**Expected behavior**
The canvas comics to show up as well..

**App version**
- v0.7-r46

**Source WITH source version**
- Webtoons 2.1.4

**Comment by TheNetsky** [comment]
@btylerh7

**Comment by btylerh7** [comment]
Because of the way that Webtoon does search on their website, it is not possible to search Original and Canvas comics at the same time. If you want to search for a Canvas comic, you can select "Canvas" in the "Search-type" option on the search page. 

![picture of search options](https://user-images.githubusercontent.com/91493312/209154188-f5f85efc-c661-40e6-ba70-ef67e52afa83.jpeg)

Hope this helps!

**Comment by gimmeamin** [comment]
thank u that works!
